### ISSUE TITLE
ComfyUI - not CompfyUI

### ISSUE THREAD

**Issue by NickyDrinks** [stavsap/generative-ai-wsl2#1]
The backend and GUI is called "ComfyUI" rather than "CompfyUI" as referred to in the documentation and scripts.  This is also carried over into the naming of the WSL2 virtual disks which, while not affecting the running of it as far as I'm aware, is mildly irritating :-)

**Comment by stavsap** [comment]
didn't notice that, thanks for pointing this out. ill fix soon.

**Comment by stavsap** [comment]
fixed
